# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres:13.5
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - back-net

  api:
    ports:
      - 8000:8000
    build: ./
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/kanba-db
      - JWT_SECRET=mysecretjwt
    networks:
      - back-net
    depends_on:
      - postgres
networks:
  back-net:
    driver: bridge
volumes:
  postgres:
